CREATE SCHEMA IF NOT EXISTS football;
CREATE ALIAS IF NOT EXISTS DATE FOR "com.jeuxwebapitest.util.H2SqlFunctions.date";

CREATE TABLE football."League" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL
);

CREATE TABLE football."Team" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    short_name VARCHAR(6) NOT NULL,
    city VARCHAR(128),
    logo_url VARCHAR(256)
);

CREATE TABLE football."Tournament" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    st_year INTEGER NOT NULL,
    fn_year INTEGER,
    league_id BIGINT NOT NULL
);

CREATE TABLE football."Stage" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    "order" INTEGER NOT NULL,
    league_id BIGINT NOT NULL,
    tournament_id BIGINT NOT NULL
);

CREATE TABLE football."Match" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour INTEGER NOT NULL,
    round VARCHAR(16) NOT NULL,
    date TIMESTAMP WITH TIME ZONE,
    h_score INTEGER NOT NULL,
    g_score INTEGER NOT NULL,
    city VARCHAR(128),
    stadium VARCHAR(128),
    league_id BIGINT NOT NULL,
    tournament_id BIGINT NOT NULL,
    stage_id BIGINT NOT NULL,
    h_team_id BIGINT NOT NULL,
    g_team_id BIGINT NOT NULL
);

ALTER TABLE football."Tournament"
    ADD CONSTRAINT fk_tournament_league_id
    FOREIGN KEY (league_id) REFERENCES football."League"(id) ON DELETE CASCADE;

ALTER TABLE football."Stage"
    ADD CONSTRAINT fk_stage_league_id
    FOREIGN KEY (league_id) REFERENCES football."League"(id) ON DELETE CASCADE;

ALTER TABLE football."Stage"
    ADD CONSTRAINT fk_stage_tournament_id
    FOREIGN KEY (tournament_id) REFERENCES football."Tournament"(id) ON DELETE CASCADE;

ALTER TABLE football."Match"
    ADD CONSTRAINT fk_match_league_id
    FOREIGN KEY (league_id) REFERENCES football."League"(id) ON DELETE CASCADE;

ALTER TABLE football."Match"
    ADD CONSTRAINT fk_match_tournament_id
    FOREIGN KEY (tournament_id) REFERENCES football."Tournament"(id) ON DELETE CASCADE;

ALTER TABLE football."Match"
    ADD CONSTRAINT fk_match_stage_id
    FOREIGN KEY (stage_id) REFERENCES football."Stage"(id) ON DELETE CASCADE;

ALTER TABLE football."Match"
    ADD CONSTRAINT fk_match_h_team_id
    FOREIGN KEY (h_team_id) REFERENCES football."Team"(id);

ALTER TABLE football."Match"
    ADD CONSTRAINT fk_match_g_team_id
    FOREIGN KEY (g_team_id) REFERENCES football."Team"(id);

CREATE INDEX idx_league_name ON football."League"(name);
CREATE INDEX idx_tournament_league_id ON football."Tournament"(league_id);
CREATE INDEX idx_tournament_st_year ON football."Tournament"(st_year);
CREATE INDEX idx_tournament_fn_year ON football."Tournament"(fn_year);
CREATE INDEX idx_tournament_name ON football."Tournament"(name);
CREATE INDEX idx_stage_league_id ON football."Stage"(league_id);
CREATE INDEX idx_stage_tournament_id ON football."Stage"(tournament_id);
CREATE INDEX idx_stage_order ON football."Stage"("order");
CREATE INDEX idx_stage_name ON football."Stage"(name);
CREATE INDEX idx_team_name ON football."Team"(name);
CREATE INDEX idx_team_short_name ON football."Team"(short_name);
CREATE INDEX idx_team_city ON football."Team"(city);
CREATE INDEX idx_match_league_id ON football."Match"(league_id);
CREATE INDEX idx_match_tournament_id ON football."Match"(tournament_id);
CREATE INDEX idx_match_stage_id ON football."Match"(stage_id);
CREATE INDEX idx_match_h_team_id ON football."Match"(h_team_id);
CREATE INDEX idx_match_g_team_id ON football."Match"(g_team_id);
CREATE INDEX idx_match_tour ON football."Match"(tour);
CREATE INDEX idx_match_round ON football."Match"(round);
CREATE INDEX idx_match_date ON football."Match"(date);
CREATE INDEX idx_match_h_score ON football."Match"(h_score);
CREATE INDEX idx_match_g_score ON football."Match"(g_score);
