quarkus.http.root-path=/api/q/v1
quarkus.smallrye-openapi.path=/api/q/v1/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/api/q/v1/swagger

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.packages=Entities
quarkus.hibernate-orm.log.sql=false
RFLeagueId=1

quarkus.index-dependency.jeuxdbcontext.group-id=com.jeuxdbcontext
quarkus.index-dependency.jeuxdbcontext.artifact-id=jeuxdbcontext

quarkus.oidc.application-type=service
quarkus.oidc.client-id=probe-app-client

# Development profile (local run)
%dev.quarkus.http.port=30881
%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/LeaguesDemo
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=Postik123
%dev.quarkus.hibernate-orm.database.default-schema=football
%dev.quarkus.oidc.auth-server-url=http://keycloak-dev:8082/realms/probe-app

# Production profile (Docker run)
%prod.quarkus.http.port=19081
%prod.quarkus.datasource.reactive.url=postgresql://host.docker.internal:5432/LeaguesDemo
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=Postik123
%prod.quarkus.hibernate-orm.database.default-schema=football
%prod.quarkus.oidc.auth-server-url=http://keycloak-dev:8082/realms/probe-app

# CORS (fully open for local development)
quarkus.http.cors=true
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS
quarkus.http.cors.headers=*
%dev.quarkus.http.cors.origins=*
%prod.quarkus.http.cors.origins=*
