quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://localhost:5432/LeaguesDemo
quarkus.datasource.username=postgres
quarkus.datasource.password=Postik123

quarkus.http.root-path=/api/q/v1
quarkus.http.port=30881

quarkus.smallrye-openapi.path=/api/q/v1/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/api/q/v1/swagger

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.database.default-schema=football
quarkus.hibernate-orm.packages=Entities
quarkus.hibernate-orm.log.sql=false
RFLeagueId=1

quarkus.index-dependency.jeuxdbcontext.group-id=com.jeuxdbcontext
quarkus.index-dependency.jeuxdbcontext.artifact-id=jeuxdbcontext

quarkus.oidc.auth-server-url=http://keycloak-dev:8082/realms/probe-app
quarkus.oidc.application-type=service
quarkus.oidc.client-id=probe-app-client
