quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/LeaguesDemo
quarkus.datasource.username=postgres
quarkus.datasource.password=Postik123

quarkus.http.port=30881

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.database.default-schema=football
quarkus.hibernate-orm.packages=Entities
quarkus.hibernate-orm.log.sql=false
