version: "3.9"

services:
  jeuxwebapi:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    image: jeuxwebapi:local
    ports:
      - "19081:19081"
    environment:
      QUARKUS_PROFILE: dev
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://host.docker.internal:5432/LeaguesDemo
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: Postik123
      QUARKUS_HTTP_PORT: 19081
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: none
      QUARKUS_HIBERNATE_ORM_DEFAULT_SCHEMA: football
      QUARKUS_HIBERNATE_ORM_PACKAGES: Entities
      QUARKUS_HIBERNATE_ORM_LOG_SQL: "false"
      RFLEAGUEID: "1"
      QUARKUS_INDEX_DEPENDENCY_JEUXDBCONTEXT_GROUP_ID: com.jeuxdbcontext
      QUARKUS_INDEX_DEPENDENCY_JEUXDBCONTEXT_ARTIFACT_ID: jeuxdbcontext
      QUARKUS_OIDC_AUTH_SERVER_URL: http://host.docker.internal:8082/realms/probe-app
      QUARKUS_OIDC_APPLICATION_TYPE: service
      QUARKUS_OIDC_CLIENT_ID: probe-app-client

