quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/LeaguesDemo
quarkus.datasource.username=postgres
quarkus.datasource.password=Postik123

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.database.default-schema=football
quarkus.hibernate-orm.packages=Entities
quarkus.hibernate-orm.log.sql=false

quarkus.http.root-path=/
quarkus.http.test-port=0

quarkus.devservices.enabled=false
quarkus.oidc.auth-server-url=http://localhost:8082/realms/probe-app
quarkus.oidc.application-type=service
quarkus.oidc.client-id=probe-app-client

quarkus.index-dependency.jeuxwebapi.group-id=com.jeuxdbcontext
quarkus.index-dependency.jeuxwebapi.artifact-id=jeuxwebapi
RFLeagueId=1

# Keycloak test token config
keycloak.auth.token-url=http://localhost:8082/realms/probe-app/protocol/openid-connect/token
keycloak.auth.client-id=probe-app-client
keycloak.auth.grant-type=password
keycloak.auth.username=testuser01
keycloak.auth.password=Test-user123
