quarkus.http.root-path=/api/q/v1

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swaggerui

quarkus.smallrye-openapi.info-title=JeuxSonde API
quarkus.smallrye-openapi.info-description=REST API for football leagues, tournaments, teams, and matches.
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-contact-name=JeuxSonde Team
quarkus.smallrye-openapi.info-contact-email=contact@example.com

quarkus.http.port=30881

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.packages=Entities
quarkus.hibernate-orm.log.sql=false
RFLeagueId=1

quarkus.index-dependency.jeuxdbcontext.group-id=com.jeuxdbcontext
quarkus.index-dependency.jeuxdbcontext.artifact-id=jeuxdbcontext
