quarkus.http.root-path=/api/q/v1

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swaggerui

quarkus.smallrye-openapi.info-title=JeuxSonde API
quarkus.smallrye-openapi.info-description=REST API for football leagues, tournaments, teams, and matches.
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-contact-name=JeuxSonde Team
quarkus.smallrye-openapi.info-contact-email=contact@example.com
